version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    command: ["sh", "-c", "PORT=3001 npm run start"]
